language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - SYMFONY_VERSION=*

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: SYMFONY_VERSION=3.3.*
    - php: 7.2
      env: SYMFONY_VERSION=3.4.*
    - php: 7.2
      env: SYMFONY_VERSION=4.1.*;ASSETIC=skip
    - php: 7.2
      env: SYMFONY_VERSION=4.2.*;ASSETIC=skip
    - php: 7.2
      env: SYMFONY_VERSION=@dev;ASSETIC=skip
    - php: 7.3
      env: SYMFONY_VERSION=3.3.*
    - php: 7.3
      env: SYMFONY_VERSION=3.4.*
    - php: 7.3
      env: SYMFONY_VERSION=4.1.*;ASSETIC=skip
    - php: 7.3
      env: SYMFONY_VERSION=4.2.*;ASSETIC=skip
    - php: 7.3
      env: SYMFONY_VERSION=@dev;ASSETIC=skip
    - php: 7.0
      env: TWIG_VERSION=1.*
    - php: 7.0
      env: TWIG_VERSION=2.*
    - php: 7.1
      env: DEPENDENCIES=beta
  allow_failures:
    - php: 7.2
      env: SYMFONY_VERSION=@dev;ASSETIC=skip

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - if [ "$ASSETIC" != "skip" ]; then composer require "kriswallsmith/assetic:^1.1" --no-update; fi;
  - if [ "$TWIG_VERSION" != "" ]; then composer require twig/twig:$TWIG_VERSION --no-update; fi
  - if [ "$DEPENDENCIES" != "" ]; then composer config minimum-stability $DEPENDENCIES; fi;

install: composer update --prefer-source $COMPOSER_FLAGS

script: ./vendor/bin/phpunit --coverage-text

notifications:
  slack: liip:3QOs1QKt3aCFxpJvRzpJCbVZ
